name: deploy serverless framework

on:
    push:
        branches: ['*']

jobs:
    deploy:
        name: deploy
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v1

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: "14.x"

            - run: |
                npm i

            - name: configure aws
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-northeast-1
            
            # - name: deploy dev
            #   if: github.ref == 'refs/heads/develop'
            #   uses: serverless/github-action@master
            #   with:
            #       args: deploy --verbose --stage dev
            #   env:
            #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            #       ENDPOINT_URL: http://api-dev.rocketfor.band
            #       YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
            #       COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID_DEV }}
            #       COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID_DEV }}
            #       COGNITO_CLIENT_SECRET: ${{ secrets.COGNITO_CLIENT_SECRET_DEV }}
            #       S3_BUCKET: rocket-auth-dev-storage

            - name: deploy
              if: github.ref == 'refs/heads/master'
              uses: serverless/github-action@master
              with:
                  args: deploy --verbose --stage prd
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  ENDPOINT_URL: https://api-v2.rocketfor.band
                  YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
                  COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
                  COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
                  COGNITO_CLIENT_SECRET: ${{ secrets.COGNITO_CLIENT_SECRET }}
                  S3_BUCKET: rocket-auth-storage
                  AUTH0_DOMAIN: https://rocket.jp.auth0.com
                  AUTH0_CLIENT_ID: oSt3IUHX3Pnk4tr68DbHZUnwmJPoTHZ6
                  AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
